### ISSUE TITLE
Remove n2o dependency

### ISSUE THREAD

**Issue by spiegela** [synrc/rest#1]
There is a lot of cross dependencies between rest and n2o.  It'd be nice if we could eliminate those so that users could use rest without having needed to pull in all of n2o.

It looks seems like it's mostly using the type conversions/checkers in "wf_convert" and "wf_utils".  Is there any interest in pulling these into a separate library-application?

**Comment by 5HT** [comment]
It is easy to remove wf_convert and wf_utils references. I will do that on week end.

**Comment by rgrinberg** [comment]
I think this is done but the readme still uses `wf:to_list`

**Comment by 5HT** [comment]
@rgrinberg is right, wf:to_list is removed from rest totally and rest has no dependency from n2o.
in readme we show how to use it with n2o anyway.
I think I can close this issue if you don't mind.

**Comment by 5HT** [comment]
removed as for 2.9.
