### ISSUE TITLE
CROSS issue

### ISSUE THREAD

**Issue by hamdijmii1992** [synrc/rest#4]
I am trying to request the rest api with an ajax call as follows:

```
$.ajax({
              url:  'http://localhost:9000/users',
              method: 'GET',
              type: 'post',
              contentType: 'applications/json',
			  success: function (response, type, xhr) {
			  console.log(response);
			   data=JSON.stringify(response);
			   console.log(data);
			   .........
```

But in my browser log I got a CROSS issue

> XMLHttpRequest cannot load http://localhost:9000/users. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

How can I resolve it ?

**Comment by m-2k** [comment]
Resolve it: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by 5HT** [comment]
what problem do you have with these lines? https://github.com/synrc/rest/blob/master/src/rest_cowboy.erl#L18:

```
{Origin, Req3} = cowboy_req:header(<<"origin">>, Req2, <<"*">>),
Req4 = cowboy_req:set_resp_header(<<"Access-Control-Allow-Origin">>, Origin, Req3),
```

Could it be answer to your question?
